// Movies actions
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_BY_CATEGORY = "FETCH_MOVIES_BY_GENRE";
export const FETCH_MOVIES_BY_KEYWORD = "FETCH_MOVIES_BY_KEYWORD";
export const FETCH_CATEGORY = "FETCH_GENRE";

// Movie actions
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_CASTS = "FETCH_MOVIE_CASTS";
export const FETCH_MOVIE_TRAILER = "FETCH_MOVIE_TRAILER";
export const FETCH_MOVIE_KEYWORDS = "FETCH_MOVIE_KEYWORDS";
export const FETCH_MOVIE_RECOMMENDATIONS = "FETCH_MOVIE_RECOMMENDATIONS";

// Actor actions
export const FETCH_ACTOR_DETAILS = "FETCH_ACTOR_DETAILS";
export const FETCH_ACTOR_POPULAR = "FETCH_ACTOR_POPULAR";
